### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'enable_cdp_events'

### ISSUE THREAD

**Issue by hanwsf** [Lukium/chatgpt-api-server#3]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from api.ChatGPT_Server import app
  File "/media/will/E/python/chatgpt-api-server-main/api/ChatGPT_Server.py", line 29, in <module>
    ChatGPTServer = asyncio.run(ChatGPTServer.create())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/media/will/E/python/chatgpt-api-server-main/classes/ChatGPTServer.py", line 50, in create
    await self.__refresh_cloudflare()
  File "/media/will/E/python/chatgpt-api-server-main/classes/ChatGPTServer.py", line 103, in __refresh_cloudflare
    Settings.API_CF_CLEARANCE, Settings.API_USER_AGENT = await Cloudflare(proxy=Settings.API_DEFAULT_PROXY).a_get_cf_cookies()
  File "/media/will/E/python/chatgpt-api-server-main/contrib/OpenAIAuth/Cloudflare.py", line 122, in a_get_cf_cookies
    driver = uc.Chrome(
  File "/home/will/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_cdp_events'

**Comment by Lukium** [comment]
Closing this since got no answer
